- name: load vars
  include_vars: vars/windows_iso.yml
- name: get list of isos
  set_fact:
    list_iso: "{{ windows_iso.win2012r2 }} + {{ windows_iso.win2016 }}"
- name: Create directory structure
  win_file:
    path: "{{ISOPath}}"
    state: directory
- name: Download windows iso(s)
  win_get_url:
    url: "{{http_fileserver}}{{ item }}"
    dest: "{{ISOPath}}{{item}}"
    force: "no"
  loop: "{{ list_iso }}"
  when: http_fileserver != 'skip'

 