---
- name: Build Image
  hosts: hyperv
  gather_facts: no
  vars:
    HostConfig: false
    convert: false 
  vars_files:
    - vars/global_vars.yml
  roles:
#    - role: prepare-host
    - role: windows-iso
    - role: prepare-build
    - role: build-image
    - role: convert-build
      when: convert == true | bool
#    - role: upload-image
      
    
