---
- name: template
  hosts: hyperv
  gather_facts: no
  vars: 
    HostConfig: false
  vars_files:
    - vars/global_vars.yml
    - vars/autounattend_setup.yml
    - vars/cloudbase_vars.yml
    - vars/windows_iso.yml
    

  roles:
    - role: convert-build

      
    
