- name: Wait for VM to shutdown
  win_shell: (get-vm -name {{os_selection}}).state
  until: vmstate.stdout.find("Off") != -1
  retries: 30
  delay: 30
  register: vmstate
  ignore_errors: true

- name: Clean up & Compact disk
  win_shell: | 
    get-vm -name {{os_selection}} | Remove-VM -Force
    Mount-VHD {{OutputPath}}{{os_selection}}.vhdx -ReadOnly
    Optimize-VHD -Path {{OutputPath}}{{os_selection}}.vhdx -Mode Full
    Dismount-VHD -Path {{OutputPath}}{{os_selection}}.vhdx
    Resize-VHD -Path {{OutputPath}}{{os_selection}}.vhdx -ToMinimumSize