http_fileserver: http://192.168.1.38/?file=
windows_iso:
  win2012r2:
    - en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso
  win2016:
    - en_windows_server_2016_x64_dvd_9718492.iso
  win2019:
    - en_windows_server_2019_updated_march_2019_x64_dvd_2ae967ab.iso