#Defaults for all - used by other plays besides templating
AdministratorPassword: "PassW0rd"

#Specific
autounattend_setup:
  win2012r2std:
    product_key: "D2N9P-3P6X9-2R39C-7RTCD-MDVJX"
    image_index: 2
  win2012r2dc:
    product_key: "W3GGN-FT8W3-Y4M27-J84CP-Q3VJ9"
    image_index: 4
  win2016std:
    product_key: "WC2BQ-8NRM3-FDDYY-2BFGV-KHKQY"
    image_index: 2
  win2016dc:
    product_key: "CB7KF-BWN84-R7R2Y-793K2-8XDDG"
    image_index: 4
  win2019std:
    product_key: "N69G4-B89J2-4G8F4-WWYCC-J464C"
    image_index: 2
  win2019dc:
    product_key: "WMDGN-G9PQG-XVVXX-R3X43-63DFG"
    image_index: 4