- name: Set os_selection fact
  set_fact:
    os_selection: "{{os_version}}{{os_edition}}"

- name: Check for repo updates
  win_shell: pushd {{GitRepoPath}}; git pull

- include_tasks: create_secondary.yml