- name: load vars
  include_vars: vars/autounattend_setup.yml
- name: cb vars
  include_vars: vars/cloudbase_vars.yml

- name: Check for repo updates
  win_shell: pushd {{GitRepoPath}}; git pull --rebase

- include_tasks: create_secondary.yml